# 服务消费者的端口号
server:
  port: 10013

# 服务消费者的名称
spring:
  application:
    name: cluster-ribbon-consumer-service

# 注册中心的集群地址
eureka:
  client:
    service-url:
      defaultZone: http://msrainbow-server-master:2222/eureka/,http://msrainbow-server-slave-one:3333/eureka/
